spring:
  application:
    name: uptrack-backend
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/uptrack_db}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:Abcd@1234}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

logging:
  level:
    org.hibernate.SQL: info
